inherited fmAbout: TfmAbout
  ActiveControl = btOk
  Caption = 'About'
  ClientHeight = 104
  ClientWidth = 248
  OnCreate = FormCreate
  ExplicitWidth = 264
  ExplicitHeight = 143
  PixelsPerInch = 96
  TextHeight = 13
  object btOk: TButton
    AlignWithMargins = True
    Left = 3
    Top = 76
    Width = 242
    Height = 25
    Align = alBottom
    Caption = 'Ok'
    ModalResult = 1
    TabOrder = 1
    ExplicitWidth = 202
  end
  object sgInfo: TStringGrid
    AlignWithMargins = True
    Left = 3
    Top = 3
    Width = 242
    Height = 67
    Align = alClient
    BevelInner = bvNone
    BevelOuter = bvNone
    BorderStyle = bsNone
    Color = clBtnFace
    ColCount = 2
    Ctl3D = False
    DefaultColWidth = 120
    DefaultRowHeight = 21
    DoubleBuffered = False
    DrawingStyle = gdsClassic
    Enabled = False
    FixedCols = 0
    RowCount = 3
    FixedRows = 0
    Options = []
    ParentCtl3D = False
    ParentDoubleBuffered = False
    ScrollBars = ssNone
    TabOrder = 0
    ExplicitWidth = 202
  end
end
